language: php

cache:
    directories:
        - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

addons:
  apt:
    packages:
    - openssh-server

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/behat
